- class01/README.md
- class02/README.md
Class01 GitHub 과제를 위한 request 입니다.
> [박경규]Class01 GitHub 과제

- class01/README.md
- class02/README.md
Class01 github issue for table contents modify.
> [kbg] Class01 GitHub work - Table

- class01/README.md
- class02/README.md
class01 GitHub 과제를 위한 issue입니다.
> [최은호] Class01 github hw3

- class01/README.md
- class02/README.md
> [장해준] Github PR 실습 - Table 수정

- class01/homework/janghaejun/hw4_pythonHW_and_math/HW4_GD.py
- class01/homework/janghaejun/hw4_pythonHW_and_math/HW4_python.py
> [장해준]python 과제 및 math 실습 #4

- class01/homework/yangseungyong/hw4_pythonHW_and_math/HW_python.py
> Class[01]_hw[4]_ysy

- class01/homework/pkg/HW4_python.py
- class01/homework/pkg/HW4_test1.py
- class01/homework/pkg/HW4_test2.py
- class01/homework/pkg/HW4_test3.py
- class01/homework/pkg/HW4_test4.py
- class01/homework/pkg/HW4_test5.py
- class01/homework/pkg/HW4_test6.py
> [박경규] Class01 HW#4 python 과제 및 math 실습

- class01/homework/pkg/HW4_python.py
- class01/homework/pkg/HW4_test1.py
- class01/homework/pkg/HW4_test2.py
- class01/homework/pkg/HW4_test3.py
- class01/homework/pkg/HW4_test4.py
- class01/homework/pkg/HW4_test5.py
- class01/homework/pkg/HW4_test6.py
- class01/homework/pkg/hw5_ANN.py
- class01/homework/pkg/hw5_perceptron.py
- class01/homework/pkg/hw5_test.py
Class01 HW#5 Perceptron & ANN 실습을 위한 PR 입니다
> [박경규] Class01 HW#5 Perceptron & ANN 실습

- class01/homework/janghaejun/hw7_RNN/hw6_GRU.py
- class01/homework/janghaejun/hw7_RNN/hw6_LSTM.py
- class01/homework/janghaejun/hw7_RNN/hw6_RNN.py
- class01/homework/janghaejun/hw7_RNN/hw6_Total.py
> [장해준]Class01 HW#7 RNN 실습

- class01/homework/HW4_python_test.py
- class01/homework/perceptronANN.py
> Class[01]_hw[4]_pcw

- class01/homework/HW4_python_test.py
- class01/homework/parkcheolwoo8334/hw6/CNN.py
- class01/homework/perceptronANN.py
> Class01 hw6 parkcheolwoo8334

- class01/homework/HW4_python_test.py
- class01/homework/parkcheolwoo8334/hw5/perceptronANN.py
- class01/homework/parkcheolwoo8334/hw6/CNN.py
- class01/homework/perceptronANN.py
> Class01 hw5 parkcheolwoo8334

- class01/mini-project/05_kimANDjang/README.md
> [미니프로젝트]05dir

- class01/mini-project/04_pkg_ceh/README.md
04_pkg_ceh 의 miniproject 를 위한 PR입니다.
> 04_pkg_ceh 의 miniproject 

- class01/mini-project/02_double_y/README.md
> add README.md

- class01/mini-project/02_double_y/double_y_posture_tracker.py
2조 프로젝트 및 발표자료 업로드 를 위한 PR 입니다
> 2조 프로젝트 및 발표자료 업로드

- class01/mini-project/README.md
> README 업데이트

- class01/mini-project/README.md
> group5 Update README.md

- class01/mini-project/README.md
> README.md 수정

- class01/mini-project/README.md
> PPT와 README 업데이트

- README.md
> group2 README.md

- class02/homework/janghaejun/HW2_LED.py
- class02/homework/janghaejun/HW2_factory.py
Class02 과제 1 LED 제어와 Factory,py 과제 제출을 위한 issue입니다.
> [jhj]Class02 hw1 LED control and Factory,py

- class02/homework/yangyeongjun/HW#1LED/LED.py
- class02/homework/yangyeongjun/HW#2factory/factory.py
> class02 HW1~2 추가

- class02/homework/pkg/HW1_led.py
- class02/homework/pkg/HW2_factory.py
Class02 과제 1 LED 제어와 Factory 과제를  위한 PR 입니다.
> [pkg] Class02 hw1-2 LED & Factory

- class02/homework/ceh/hw1_led.py
- class02/homework/ceh/hw2_factory.py
Class02 과제 1 LED 제어와 Factory 과제를 위한 PR 입니다.
> [ceh]Class02 hw1-2 LED , Factory

- class02/homework/khs/hw1/hw1_LED.py
- class02/homework/khs/hw1_LED.py
> Class02 hw1 khs

- class02/homework/khs/hw1/hw1_LED.py
- class02/homework/khs/hw1_LED.py
- class02/homework/khs/hw2/hw2_factory.py
Class02_hw2_멀티쓰레딩_카메라_출력_구현 제출 PR입니다.
> Class02 hw2 khs

- README.md
> 2조 README.md 수정을 위한 PR입니다.

- README.md
> 2조 readme update

- README.md
> team2_ppt_adress
